#!/usr/bin/env bash
# This script checks if a host is online by pinging its IP address

# Check if the argument is passed
if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Get the IP address from the argument
IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"
