#!/usr/bin/env bash
# This script displays all active IPv4 IP addresses on the machine

ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | \
awk '{ print $2 }' | grep -v '^127\.'
echo "127.0.0.1"
